### ISSUE TITLE
Return empty PNG and empty JSON if images array is empty

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/spritezero#11]
Currently, passing an empty array into `spritezero.generateImage` throws an error (ref #10). The better behavior would be to return an empty PNG, possibly with an error that indicated that the image layout did not have any SVG's.

**Comment by tmcw** [comment]
Upstream in node-mapnik: `mapnik.blend` should accept zero-length arrays

**Comment by jakepruitt** [comment]
@tmcw any way we could change our usage of `mapnik.blend` to `image.composite` as described in #7?

@springmeyer or @flippmoke, are there specific reasons `mapnik.blend` throws an error for zero-length arrays?

**Comment by tmcw** [comment]
So! PNG images can't be 0x0. How about a blank response?

**Comment by bsudekum** [comment]
I don't think it makes sense to feed spritezero an empty array and expect it to respond with a valid (blank) png. It actually seems logical for spritezero to only work if the the array length > 0.

**Comment by jfirebaugh** [comment]
@bsudekum Why not? It simplifies all the downstream code and eliminates an unnecessary boundary condition.

**Comment by bsudekum** [comment]
this is done
