### ISSUE TITLE
map one image to multiple image names

### ISSUE THREAD

**Issue by peterqliu** [mapbox/spritezero#17]
In the context of Mapbox GL sprites, I often use the same symbol to differently-named amenities (`police` and `prison`, for example). Instead of keeping track of multiple identical images, I'd like a way to map multiple names to one image. 

Practically, in the sprite json, this means multiple sprite objects referring to the same pixel coords.

Benefits:

Major: Updates to images will automatically apply to all its referents, without danger of forgetting one and having them fall out of sync.

Minor: Will need only one instance of each symbol in the PNG sheet, saving a few bytes here and there.

**Comment by tmcw** [comment]
Do you have any suggestion for how this would work on the UI level, spritezero level, or spritezero-cli? I don't see a clear way to implement this that would make it worthwhile to implement.

**Comment by jfirebaugh** [comment]
This would add complexity all along the assets stack, from spritezero / mapnik all the way to the UI.

I think we're much better of just having individual icons that happen to be the same.
