### ISSUE TITLE
Does not recognize stroke-dasharray

### ISSUE THREAD

**Issue by brentlemons** [mapbox/spritezero#18]
Stroke-dasharray is ignored. Renders as solid line. Tried with both <circle> and <line>.

**Comment by tmcw** [comment]
This would be upstream in Mapnik - @springmeyer @jakepruitt any idea about support/potential of support for dasharray>

**Comment by springmeyer** [comment]
Checked in Mapnik and yes, support for drawing dashed lines is missing from the [structure used to pass around drawing commands](https://github.com/mapnik/mapnik/blob/master/include/mapnik/svg/svg_path_attributes.hpp) and from the [SVG rasterization code] (https://github.com/mapnik/mapnik/blob/master/include/mapnik/svg/svg_renderer_agg.hpp). Adding this should be feasible, probably a day or two of work. Proposed next actions:

  - [ ] Create ticket upstream at https://github.com/mapnik/mapnik/issues with testcase (@jakepruitt)
  - [ ] Create plan for adding this feature (@jakepruitt and @artemp)

**Comment by artemp** [comment]
Should we change to ? /cc @springmeyer @jakepruitt 
```diff
diff --git a/include/mapnik/marker.hpp b/include/mapnik/marker.hpp
index 3aaa1cd..d8e1b12 100644
--- a/include/mapnik/marker.hpp
+++ b/include/mapnik/marker.hpp
@@ -115,11 +115,11 @@ public:
 
     inline double width() const
     {
-        return vector_data_->bounding_box().width();
+        return vector_data_->width();
     }
     inline double height() const
     {
-        return vector_data_->bounding_box().height();
+        return vector_data_->height();
     }
 
     mapnik::svg_path_ptr get_data() const
```

**Comment by springmeyer** [comment]
@artemp please provide some context on why you are asking?

**Comment by artemp** [comment]
@springmeyer - wrong repo, sry :)

**Comment by artemp** [comment]
^ wrong repo, moved to https://github.com/mapnik/mapnik/issues/3224

**Comment by springmeyer** [comment]
spritezero has supported `stroke-dasharray` for some time now after upgrading to mapnik after this fix: https://github.com/mapnik/mapnik/issues/3223
