### ISSUE TITLE
Rendering artifacts

### ISSUE THREAD

**Issue by edenh** [mapbox/spritezero#3]
I'm getting some dark antialiasing artifacts in generated sprites. Here is a sample output:

![sprite](https://cloud.githubusercontent.com/assets/1577766/9240322/8f3383d2-4119-11e5-9d2a-41dbca62a84c.png)

When used in a style:

![screen shot 2015-08-12 at 5 41 01 pm](https://cloud.githubusercontent.com/assets/1577766/9240346/d4cb6bd0-4119-11e5-8376-00b551ef1e51.png)

**Comment by edenh** [comment]
cc @jakepruitt

**Comment by edenh** [comment]
@flippmoke a simple test case:
https://dl.dropboxusercontent.com/u/1864811/sample.zip

**Comment by flippmoke** [comment]
@artemp ^

**Comment by artemp** [comment]
@edenh  @flippmoke - looks like alpha blending issue. I need more context to figure out if this is mapnik-core or something else. One thing to try is to initialise sprite image to rgba(255,255,255,1.0) before rasterising SVG's.

**Comment by artemp** [comment]
@flippmoke - try this patch and lets sync up when you're up

```diff
diff --git a/src/mapnik_image.cpp b/src/mapnik_image.cpp
index 354dbf6..b05501a 100644
--- a/src/mapnik_image.cpp
+++ b/src/mapnik_image.cpp
@@ -1,4 +1,3 @@
-
 // mapnik
 #include <mapnik/color.hpp>             // for color
 #include <mapnik/image.hpp>             // for image types
@@ -2265,6 +2264,7 @@ Local<Value> Image::_fromSVGSync(bool fromFile, _NAN_METHOD_ARGS)
         }
 
         mapnik::image_rgba8 im(svg_width, svg_height);
+        im.set(0x00ffffff);
         agg::rendering_buffer buf(im.bytes(), im.width(), im.height(), im.row_size());
         pixfmt pixf(buf);
         renderer_base renb(pixf);
@@ -2439,6 +2439,7 @@ void Image::EIO_FromSVG(uv_work_t* req)
         }
 
         mapnik::image_rgba8 im(svg_width, svg_height);
+        im.set(0x00ffffff);
         agg::rendering_buffer buf(im.bytes(), im.width(), im.height(), im.row_size());
         pixfmt pixf(buf);
         renderer_base renb(pixf);
@@ -2616,6 +2617,7 @@ void Image::EIO_FromSVGBytes(uv_work_t* req)
         }
 
         mapnik::image_rgba8 im(svg_width, svg_height);
+        im.set(0x00ffffff);
         agg::rendering_buffer buf(im.bytes(), im.width(), im.height(), im.row_size());
         pixfmt pixf(buf);
         renderer_base renb(pixf);
```

**Comment by flippmoke** [comment]
Please try again with node mapnik `3.4.3` @edenh

**Comment by edenh** [comment]
@flippmoke looks great! Going to update mapnik and add a test svg.
