### ISSUE TITLE
the module i can't install 

### ISSUE THREAD

**Issue by liwanchong04719** [mapbox/spritezero#46]
any of node's versions  i can't install the spritezero  can you tell me  how  to do

**Comment by bhousel** [comment]
Can you share the output of `npm install spritezero` ?

**Comment by liwanchong04719** [comment]
@bhousel 
> mapnik@3.6.0 install D:\code\mapbox\createSprite\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.0/node-v48-win32-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.6.0 and node@6.10.0 (node-v48 ABI) (falling back to source compile with node-gyp)

D:\code\mapbox\createSprite\node_modules\mapnik>if not defined npm_config_node_gyp (node "D:\nvm\v6.10.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean
)

D:\code\mapbox\createSprite\node_modules\mapnik>if not defined npm_config_node_gyp (node "D:\nvm\v6.10.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build
 --module=D:\code\mapbox\createSprite\node_modules\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=D:\code\mapbox\createSprite\node_modules\mapnik\lib\binding )  else (node "" configure --fallback
-to-build --module=D:\code\mapbox\createSprite\node_modules\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=D:\code\mapbox\createSprite\node_modules\mapnik\lib\binding )
'mapnik-config' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
gyp: Call to 'mapnik-config --ldflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\nvm\v6.10.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\nvm\\v6.10.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\code\\mapbox\\createSprite\\nod
e_modules\\mapnik\\lib\\binding\\mapnik.node" "--module_name=mapnik" "--module_path=D:\\code\\mapbox\\createSprite\\node_modules\\mapnik\\lib\\binding"
gyp ERR! cwd D:\code\mapbox\createSprite\node_modules\mapnik
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\code\mapbox\createSprite\node_modules\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=D:\co
de\mapbox\createSprite\node_modules\mapnik\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\code\mapbox\createSprite\node_modules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\code\\mapbox\\createSprite\\node_modules\\mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\code\mapbox\createSprite\node_modules\mapnik
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\code\mapbox\createSprite\node_modules\mapnik\lib\binding\mapnik.node --module_name=mapnik --module_path=D:\code\mapbox\createSprite\node_mod
ules\mapnik\lib\binding' (1)
npm WARN createsprite@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@mapbox/spritezero" "--save-devv"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.6.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.6.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\code\mapbox\createSprite\npm-debug.log

**Comment by jingsam** [comment]
Use an VPN if you want to install spritezero in China.

**Comment by bhousel** [comment]
@liwanchong04719, can you try the install with a VPN and let us know if this can be closed?

**Comment by danger89** [comment]
same issue, I'm not living in China ><

**Comment by StuRuby** [comment]
I use node@v8 works for me!

**Comment by petitlen** [comment]
the same for me!
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error

**Comment by fvanwijk** [comment]
Same for me in Node 10 on Windows. Switching to Node 8 works for me.

**Comment by mjcc007** [comment]
the same for me , do have the other ways of install?

**Comment by jingsam** [comment]
Note that spritezero depend on node-mapnik, and node-mapnik drops windows support since v3.7.0.

**Comment by springmeyer** [comment]
Going to close this ticket. If anyone is having trouble installing the latest versions of spritezero, please create new issues detailing the spritezero version and your node version. @jingsam is correct that the versions supported will depend on the versions supported by node-mapnik.

**Comment by JeongJun-Lee** [comment]
Works Node 10 on Mac.
