### ISSUE TITLE
change arguments in generateLayout to options

### ISSUE THREAD

**Issue by allierowan** [mapbox/spritezero#47]
We'd like the ability to pass max_size to spritezero (and ultimately to mapnik) and think that using options arguments is the right choice. This would be a breaking change. 

This is related to [this PR](https://github.com/mapbox/api-styles/issues/571) regarding errors we got when the pixel limit for sprites in mapnik was changed. This would allow max_size to be editable, and also allow us to test our fix for sprites that got uploaded before the limit was updated that are now throwing errors (we are going to drop the oversized icons from the spritesheet and then send it back). 

I'll get started on a PR for this.

FYI @bsudekum @bhousel

**Comment by bhousel** [comment]
Cool, passing as an options object sounds good to me  👍

**Comment by allierowan** [comment]
Awesome, thanks @bhousel. Could you give me a code review (or recommend someone) when you get a chance? https://github.com/mapbox/spritezero/pull/48

**Comment by bhousel** [comment]
This was done..
