### ISSUE TITLE
spritezero-cli is producing blurry images for some svgs, maybe anti-aliased

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/spritezero#50]
spritezero-cli version 2.0.0
spritezero version 4.0.1

Source svg: https://gist.github.com/JesseCrocker/c813239c149b7849d5efd733cf88eb3f

Comparison between output from spritezero and convert(Imagemagick)
<img width="1541" alt="screen shot 2017-06-08 at 12 52 08 pm" src="https://user-images.githubusercontent.com/2048291/26946272-f46a5502-4c4b-11e7-8444-07b7d462d68b.png">

spritezero output:
![spritezero](https://user-images.githubusercontent.com/2048291/26946293-0033c40e-4c4c-11e7-9698-32ff07aac6f2.png)

imagemagick output:
![imagemagick](https://user-images.githubusercontent.com/2048291/26946306-0a1df340-4c4c-11e7-8225-3193cf67342b.png)

**Comment by springmeyer** [comment]
For reference, this is the svg rendered with Mapnik v3.0.x's `svg2png`utility:

![source](https://user-images.githubusercontent.com/20300/27403495-76ff80e0-567f-11e7-8e93-8287a63d741f.png)

To my eye it looks somewhere between the spritezero output and the imagemagick output. Spritezero under the hood rasterizes with mapnik and then lays out with node-mapnik.blend. It may be that the blend step is introducing slightly more blurring. I'm not sure if this is avoidable.

**Comment by springmeyer** [comment]
> It may be that the blend step is introducing slightly more blurring. I'm not sure if this is avoidable.

I don't think this is easily avoidable. Not without snapping the svg location to an integer grid, which is not something I see myself or others having time to invest in. If someone is interested in diving deeper into this issue, please comment, but for now I'll close.
