### ISSUE TITLE
Use Async interfaces to svg rasterization and image encoding

### ISSUE THREAD

**Issue by springmeyer** [mapbox/spritezero#6]
After bugs are solved like #3, it would likely help performance to start using the async interfaces node-mapnik provides. So `mapnik.Image.fromSVGBytes` and `image.encode` instead of their sync versions currently in use at https://github.com/mapbox/spritezero/blob/bd25089b0d5c880393e7cb24bb4fdf20e7de0767/index.js#L19-L20

**Comment by bsudekum** [comment]
All done
