### ISSUE TITLE
Error: SVG parse error: Unable to parse '��ࡱ�

### ISSUE THREAD

**Issue by eduboxgithub** [mapbox/spritezero#64]
I'm trying to export an atlas using a bouch of SVG.

When I run the command spritezero sprite export_svg I get the following error:

```
$ spritezero sprite export_svg
C:\Users\myuser\AppData\Roaming\npm\node_modules\@mapbox\spritezero-cli\bin\spritezero:85
        if (err) throw err;
                 ^

Error: SVG parse error:
Unable to parse '��ࡱ�
```

**Comment by eduboxgithub** [comment]
My SVG folder had an hidden file "THUMBS.DB".

I had to debug the script and found the hidden file looking at the logs.

I added an extra validation:

```
filepaths(input).forEach(function (file)
{
	**if (file.indexOf(".svg") !== -1)**
		q.defer(loadFile, file);
});
```

**Comment by springmeyer** [comment]
Glad you could workaround this problem. In the future if you have issues related to the CLI tool, please file an issue at https://github.com/mapbox/spritezero-cli/issues instead (since it looks like that is the tool you are using here).
