### ISSUE TITLE
Install failed on windows 10 + nodejs 10

### ISSUE THREAD

**Issue by eddy-deng** [mapbox/spritezero#67]
Hi all,
I have known that spritezero dropped support for Windows from version 6.0.0. 
Now, I really want to use spritezero in my project. So, I can't install spritezero with any version? 
Could you please help me check it? I think spritezero dropped support for Windows from version 6.0.0 only and I can use older version, such as: 5.1.0 or 5.0.0

**Comment by jingsam** [comment]
Yes, you can use 5.1.0 with nodejs 4 or 8

**Comment by eddy-deng** [comment]
I understood. So, I need to downgrade nodejs version for install spritezero. 
I think I should closed.

**Comment by springmeyer** [comment]
@jingsam is correct. Because node-mapnik is used in this project and node-mapnik dropped windows support, only older versions will work on windows.
