### ISSUE TITLE
svgo should be more than just dev-dependency?

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/spritezero#72]
#68 introduced svgo into the library, however this was only made a dev-dependency. This causes issues when spritezero is a dependency of another library as it won't install svgo and will then crash when it can't find it.

It looks like either svgo will need to be a strict dependency or the methods that svgo requires pulled out of index.js?

@kkaefer

**Comment by kkaefer** [comment]
Yes, you're right. PR is in https://github.com/mapbox/spritezero/pull/73
