### ISSUE TITLE
Spritezero does not handle SVG RGB color

### ISSUE THREAD

**Issue by NasH5169** [mapbox/spritezero#86]
Hello,

I'm trying to generate a sprite from basic SVG icons.

Some of my SVG icons has "rgb style" colors like:

`rgb(71.764708%,6.27451%,10.196079%)`

instead of basic hex codes.

The final sprite shows the icon but in gray. The color has been lost.

Any idea? Bug?

Thanks.

**Comment by jseppi** [comment]
@NasH5169: `spritezero` uses `mapnik` under-the-hood for SVG rasterization. `mapnik` only supports colors specified in `HEX`, per https://github.com/mapnik/mapnik/wiki/SVG-support.

**Comment by NasH5169** [comment]
OK. Thank you very much.
