### ISSUE TITLE
Deformed png output

### ISSUE THREAD

**Issue by mrlotfi** [mapbox/spritezero#89]
I get a wrong png output with the following svg file. It's independent of the output sprite's resolution, so I guess there's a problem with the svg reader module. I have also included a screenshot of how the real svg file looks like.

`<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" width="20" height="24" viewBox="0 0 20 24"><title>PoI_Icon</title><ellipse cx="10" cy="22.42" rx="3.19" ry="0.63" opacity="0.06"/><ellipse cx="10" cy="22.56" rx="3.82" ry="0.88" opacity="0.06"/><ellipse cx="10" cy="22.41" rx="1.99" ry="0.42" opacity="0.06"/><path d="M18.82,10.56A8.82,8.82,0,1,0,7.19,18.91a4.4,4.4,0,0,1,2.37,3.65h.85a4.42,4.42,0,0,1,2.38-3.64A8.81,8.81,0,0,0,18.82,10.56Z" fill="#80bb61"/><path d="M10,1.73a8.82,8.82,0,0,1,2.79,17.19,4.42,4.42,0,0,0-2.38,3.64H9.56a4.4,4.4,0,0,0-2.37-3.65,8.82,8.82,0,0,1,1-17A9.19,9.19,0,0,1,10,1.73M10,.56A10.42,10.42,0,0,0,8,.75,10,10,0,0,0,6.82,20c.68.23,2.74,1.65,2.74,2.53h.85c0-.88,2.05-2.29,2.75-2.52A10,10,0,0,0,10,.56Z" fill="#fff" opacity="0.6"/><path d="M12.84,15c-1.12-.1-.9,0-1.34-.16a2.33,2.33,0,0,1-.78-1.63c0-.53-.14-.83.11-1.08s.55-.41.75-.59.65-.61.81-.55a1.6,1.6,0,0,0,.92.23c.61,0,1.41-.64,1.41-2.35,0-1.26-1.84-1.28-1.84-1.28S12.8,6,11.66,6c-.8,0-1,.09-1,.15,0-.18-.15-.86-1.14-.86A1.53,1.53,0,0,0,8.12,6.47S8,6.23,7.24,6.23A1.35,1.35,0,0,0,6,7.53a.79.79,0,0,0,.42.79s-1.1,0-1.1,1.47A1.67,1.67,0,0,0,6.9,11.63c.55,0,.52-.27.71-.27a8,8,0,0,1,1.93,2.18c.06.49,0-.41,0,0S9.36,15,8.48,15s-2.75,0-2.73.66h8.46S14,15.05,12.84,15ZM9.52,12l-.94-1.22.62-.59a4.37,4.37,0,0,1,.34.88A1.43,1.43,0,0,1,9.52,12Z" fill="#fff"/></svg>`

![maki](https://user-images.githubusercontent.com/9977153/106004531-8e2d6f00-60c8-11eb-9417-df8827afe5c6.png)
![image](https://user-images.githubusercontent.com/9977153/106004641-a8674d00-60c8-11eb-8ee9-c61b59e41005.png)

**Comment by artemp** [comment]
@mrlotfi Thanks for posting. This issue has been fixed in `spritezero` >= [6.2.0](https://github.com/mapbox/spritezero/tree/v6.2.0). The relevant part is upgrading to `node-mapnik` [v4.4.0](https://github.com/mapnik/node-mapnik/tree/v4.4.0)  which provides necessary fixes to SVG rendering.
So I suspect you're using an older version?

**Comment by mrlotfi** [comment]
I guess was using version 5.0.0. Thanks a lot for your help!
