### ISSUE TITLE
icons jumping around

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/spritezero#9]
![sprite-jumping](https://cloud.githubusercontent.com/assets/5607844/9284462/09084670-42aa-11e5-9185-d31333190e2a.gif)

/cc @edenh

**Comment by tmcw** [comment]
It's very unlikely this is a spritezero bug: spritezero generates one image per sprite. This is probably on the mapbox-gl-js side.

**Comment by nickidlugash** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/1430
